name: Python Integration Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  python-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.11-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.11-
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bin/requirements.txt
      - name: Build Rust project
        run: cargo build --release
      - name: Run Python integration tests
        run: |
          cd ${{ github.workspace }}
          python bin/integration_test.py
      - name: Run Python microbenchmark (optional)
        run: |
          cd ${{ github.workspace }}
          python bin/microbenchmark.py || echo "Microbenchmark completed with warnings"
        continue-on-error: true
